import shutil
from pathlib import Path
from datetime import datetime
import json

class BubblyExporter:
    def __init__(self, messages, media_folder, output_folder, metadata, templates_folder):
        self.messages = messages
        self.media_folder = Path(media_folder)
        self.output_folder = Path(output_folder)
        self.metadata = metadata
        self.templates_folder = Path(templates_folder)
        self.output_folder.mkdir(parents=True, exist_ok=True)
        (self.output_folder / "media").mkdir(exist_ok=True)

    # ----------------------
    # Load template file
    # ----------------------
    def _load_template(self, file_name: str):
        path = self.templates_folder / file_name
        if not path.exists():
            raise FileNotFoundError(f"Template not found: {path}")
        return path.read_text(encoding="utf-8")

    # ----------------------
    # Copy media files
    # ----------------------
    def _copy_media(self):
        copied_count = 0
        for msg in self.messages:
            if msg.get("media"):
                src = self.media_folder / msg["media"]
                if src.exists():
                    shutil.copy(src, self.output_folder / "media" / msg["media"])
                    copied_count += 1
        return copied_count

    # ----------------------
    # Export messages as JSON
    # ----------------------
    def _export_json(self):
        json_path = self.output_folder / "chat.json"
        messages_json = []
        for msg in self.messages:
            messages_json.append({
                "sender": msg["sender"],
                "content": msg["content"],
                "timestamp": msg["timestamp"],
                "media": msg.get("media"),
                "is_owner": msg.get("is_owner"),
                "is_group_chat": self.metadata.get("is_group_chat", False)
            })
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(messages_json, f, ensure_ascii=False, indent=2)
        return json_path.name

    # ----------------------
    # Export HTML
    # ----------------------
    def export_html(self, output_html_name="chat.html"):
        copied_count = self._copy_media()
        json_file = self._export_json()
        generated_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # ----------------------
        # Metadata header
        # ----------------------
        meta = self.metadata
        header_html = f"""
        <div class="report-header" style="padding:10px; margin-bottom:20px; background:#ddd; border-radius:10px;">
            <p><strong>Report generated by:</strong> {meta.get('user')}</p>
            <p><strong>Report generated at:</strong> {generated_time}</p>
            <p><strong>Case number:</strong> {meta.get('case')}</p>
            <p><strong>Chat name:</strong> {meta.get('chat_name')}</p>
            <p><strong>Source:</strong> {meta.get('source')}</p>
            <p><strong>WhatsApp account name:</strong> {meta.get('wa_account_name')}</p>
            <p><strong>WhatsApp account number:</strong> {meta.get('wa_account_number')}</p>
            <p><strong>Group chat:</strong> {meta.get('is_group_chat')}</p>
            <p><strong>Platform:</strong> {meta.get('platform')}</p>
            <p><strong>Media files copied:</strong> {copied_count}</p>
        </div>
        """

        # ----------------------
        # Load templates
        # ----------------------
        html_template = self._load_template("chat.html")
        css_content = self._load_template("style.css")
        js_content = self._load_template("chat.js")

        # ----------------------
        # Inline CSS & JS
        # ----------------------
        html_content = html_template.replace(
            '<link rel="stylesheet" href="style.css">',
            f"<style>{css_content}</style>"
        ).replace(
            '<script src="chat.js"></script>',
            f"<script>{js_content}</script>"
        ).replace(
            "{{header}}", header_html
        ).replace(
            #"{{messages_json_path}}", json_file
            "{{messages_json_content}}", json.dumps(self.messages, ensure_ascii=False)
        )

        # ----------------------
        # Write final HTML
        # ----------------------
        output_html_path = self.output_folder / output_html_name
        with open(output_html_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"HTML saved to {output_html_path} with inline CSS/JS")
